"""SHACL shapes for the static conformance clauses.

The division of labour this file exists to make real:

    SHACL validates the policy document.
    The gate decides the request.

Section 3 of the specification has five conformance clauses. Four of them are
statements about a document that exists, which is exactly what SHACL is for,
and until now they were checked only by `croissant_policy/validate.py`, which
inspects the JSON structurally and does not parse JSON-LD. Structural checking
is not wrong, but it cannot see what a document *means* after expansion -- an
aliased term, a `@graph` wrapper, a node reached by reference rather than
nesting -- and the profile's own threats section said so.

The fifth clause is not expressible here and the shapes say so rather than
quietly omitting it. Clause 1 is a statement about a *different* document: the
one left after every `cpol:` term is removed. SHACL constrains the graph it is
given, not a graph derived from it by deletion, so clause 1 stays with
`tests/test_degradation.py`, which performs the strip and validates the result.

Nothing here decides anything. A document can satisfy every shape below and
still be refused for every request it receives, because these constrain how a
policy is written and not what it permits. That distinction is the reason the
profile does not use SHACL as its evaluator: the object of a decision is a
request context supplied at call time, which is in no graph until someone puts
it in one, and the SHACL-SPARQL fragment that could express the check carries no
bound on evaluation.

The shapes are generated so that the closed operator set has one definition. A
hand-written copy of the five operators would be a second place to forget to
update, and the whole argument for closing the set is that the document tells
you what will be evaluated.
"""

from __future__ import annotations

from pathlib import Path

from .vocab import CPOL_NS, CROISSANT_IRI, OPERATORS, PROFILE_IRI, PROFILE_VERSION

SHACL_NS = "http://www.w3.org/ns/shacl#"
SCHEMA_NS = "https://schema.org/"
DCT_NS = "http://purl.org/dc/terms/"

_HEADER = """\
# SHACL shapes for the Croissant Policy Profile {version}
#
# Generated by croissant_policy/shapes.py. Do not edit: the closed operator set
# has one definition, in croissant_policy/vocab.py, and this file is derived
# from it. tests/test_shapes.py fails if the served file and the generator
# disagree.
#
# Scope. These validate a *document*. They do not decide a *request*, and no
# SHACL shape in this profile ever will -- see the module docstring of
# croissant_policy/shapes.py for why the two are different jobs.
#
# Conformance clause 1 (additivity: stripping every cpol: term leaves a valid
# Croissant document) is deliberately absent. It is a statement about the
# document that remains after a deletion, and SHACL constrains the graph it is
# handed rather than a graph derived from it. That clause is checked by
# performing the strip: tests/test_degradation.py.
#
# Note on cpol:operator. Its value is a string literal and not an IRI, because
# the profile's JSON-LD context does not type the term as @vocab. The shapes
# describe the profile as it is rather than as it might have been designed; the
# operator set is closed at a version, so changing this would be a version bump
# and would invalidate every document already emitted.
#
# Note on string datatypes, which cost an hour to find. Croissant's own context
# sets "@language": "en", so every plain string in a conforming document expands
# to an rdf:langString and not to an xsd:string. Shapes asserting
# sh:datatype xsd:string therefore fail on every conforming document, and the
# first draft of this file did. String-valued properties below constrain
# sh:nodeKind and lexical form instead, which holds whether or not a document
# carries a language tag. cpol:operator is checked with sh:pattern rather than
# sh:in for the same reason: sh:in compares RDF terms, and "cpol:min"@en is not
# the term "cpol:min".
#
# Note on conformsTo, which is the sharper version of the same problem and is a
# defect in Croissant rather than in this profile. Croissant's context defines
# conformsTo as dct:conformsTo without "@type": "@id", so the values of the one
# property whose job is to identify a profile expand to language-tagged strings
# instead of to IRIs, and RDF-level profile discovery does not work. Writing
# them as {{"@id": ...}} fixes the RDF and is rejected by MLCommons' own
# mlcroissant, which string-compares conformsTo to determine the Croissant
# version. Clause 2 below therefore matches either form. Reported in SPEC
# section 9; the shapes are where it was found.

@prefix sh:   <{shacl}> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix dct:  <{dct}> .
@prefix sc:   <{schema}> .
@prefix cpol: <{cpol}> .
@prefix cpsh: <{profile}#shapes/> .

"""


def _iri_pattern(iri: str) -> str:
    """A regex matching the lexical form of an IRI written as a literal.

    Needed because `conformsTo` values are literals and not IRIs in a
    conforming document -- see `vocab.conformance_claim` for why that is
    Croissant's constraint rather than this profile's choice. `sh:hasValue`
    compares RDF terms and cannot match a literal against an IRI, and
    `sh:in` cannot match a language-tagged literal against a plain one, so
    clause 2 is expressed as a pattern over the lexical form. The shapes accept
    the IRI form too, so a document written the correct RDF way still passes.
    """
    return "^" + iri.replace(".", r"\\.").replace("?", r"\\?") + "$"


def _operator_pattern() -> str:
    """The closed set, as a regex over the lexical form of the operator term.

    A pattern rather than `sh:in`, because `sh:in` compares RDF terms and
    Croissant's context language-tags every plain string: the document carries
    `"cpol:min"@en`, which is not the term `"cpol:min"`. `sh:pattern` matches
    the lexical form and is indifferent to the tag.
    """
    alternatives = "|".join(term.split(":", 1)[1] for term in sorted(OPERATORS))
    return f"^cpol:({alternatives})$"


def shapes() -> str:
    """The shapes graph, as Turtle."""
    return _HEADER.format(
        version=PROFILE_VERSION,
        shacl=SHACL_NS,
        dct=DCT_NS,
        schema=SCHEMA_NS,
        cpol=CPOL_NS,
        profile=PROFILE_IRI,
    ) + f"""\
#-----------------------------------------------------------------------------
# Clause 2 and clause 3: the dataset node.
#
# Targeted by class rather than by the presence of cpol:policy, so that a
# Croissant dataset carrying a malformed policy is reported as violating the
# profile instead of silently falling outside the shape's target and passing.
#-----------------------------------------------------------------------------

cpsh:DatasetShape
    a sh:NodeShape ;
    sh:targetClass sc:Dataset ;
    sh:name "Croissant dataset carrying a policy" ;

    # Clause 3. Exactly one policy. More than one is not a document this
    # profile can evaluate: choosing among them would be a guess about which
    # rules apply, and a guess is what the profile exists to remove.
    sh:property [
        sh:path cpol:policy ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:class cpol:Policy ;
        sh:message "Clause 3: the dataset node must carry exactly one cpol:policy, and its value must be a cpol:Policy node." ;
    ] ;

    # Clause 2, both halves. A document that claims the profile without
    # claiming Croissant is claiming a layer over nothing.
    sh:property [
        sh:path dct:conformsTo ;
        sh:minCount 2 ;
        sh:message "Clause 2: conformsTo must name both Croissant and the profile." ;
    ] ;
    sh:property [
        sh:path dct:conformsTo ;
        sh:qualifiedValueShape [
            sh:or ( [ sh:hasValue <{CROISSANT_IRI}> ] [ sh:pattern "{_iri_pattern(CROISSANT_IRI)}" ] )
        ] ;
        sh:qualifiedMinCount 1 ;
        sh:message "Clause 2: conformsTo must include <{CROISSANT_IRI}>." ;
    ] ;
    sh:property [
        sh:path dct:conformsTo ;
        sh:qualifiedValueShape [
            sh:or ( [ sh:hasValue <{PROFILE_IRI}> ] [ sh:pattern "{_iri_pattern(PROFILE_IRI)}" ] )
        ] ;
        sh:qualifiedMinCount 1 ;
        sh:message "Clause 2: conformsTo must include <{PROFILE_IRI}>." ;
    ] .


#-----------------------------------------------------------------------------
# Clause 4 and the shape of a policy.
#-----------------------------------------------------------------------------

cpsh:PolicyShape
    a sh:NodeShape ;
    sh:targetClass cpol:Policy ;
    sh:name "cpol:Policy" ;

    # Clause 4. Not a mode switch -- there is no permissive mode to switch to.
    # A document that omits it is a document whose author's intent is unknown,
    # and the evaluator refuses every action rather than assuming the
    # convenient reading.
    sh:property [
        sh:path cpol:failClosed ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:datatype xsd:boolean ;
        sh:hasValue true ;
        sh:message "Clause 4: cpol:failClosed must be present and true. There is no conforming permissive mode." ;
    ] ;

    sh:property [
        sh:path cpol:state ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:nodeKind sh:Literal ;
        sh:minLength 1 ;
        sh:message "A policy must declare the dataset's current lifecycle state." ;
    ] ;

    # An empty action list is not a policy that permits nothing; it is a policy
    # that says nothing, and silence is not auditable (SPEC 5.1).
    sh:property [
        sh:path cpol:permissibleAction ;
        sh:minCount 1 ;
        sh:class cpol:Action ;
        sh:message "A policy must declare at least one cpol:Action. An empty list is silence, not a refusal." ;
    ] ;

    sh:property [
        sh:path cpol:retentionDays ;
        sh:maxCount 1 ;
        sh:datatype xsd:integer ;
        sh:minInclusive 0 ;
    ] .


#-----------------------------------------------------------------------------
# Actions.
#-----------------------------------------------------------------------------

cpsh:ActionShape
    a sh:NodeShape ;
    sh:targetClass cpol:Action ;
    sh:name "cpol:Action" ;

    sh:property [
        sh:path cpol:actionName ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:nodeKind sh:Literal ;
        sh:minLength 1 ;
        sh:message "An action must have exactly one non-empty cpol:actionName." ;
    ] ;

    sh:property [
        sh:path cpol:requiresState ;
        sh:nodeKind sh:Literal ;
        sh:minLength 1 ;
    ] ;

    sh:property [
        sh:path cpol:condition ;
        sh:class cpol:Condition ;
    ] .


#-----------------------------------------------------------------------------
# Clause 5: conditions and the closed operator set.
#-----------------------------------------------------------------------------

cpsh:ConditionShape
    a sh:NodeShape ;
    sh:targetClass cpol:Condition ;
    sh:name "cpol:Condition" ;

    sh:property [
        sh:path cpol:conditionName ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:nodeKind sh:Literal ;
        sh:minLength 1 ;
        sh:message "A condition must have exactly one non-empty cpol:conditionName." ;
    ] ;

    # Clause 5. Note what this does and does not mean. A document using an
    # operator outside the set is non-conforming, which is what this reports.
    # It is *not* an error at evaluation time: the evaluator refuses the
    # request instead, because a rule it cannot check must stop the work rather
    # than be skipped. Validation and evaluation disagree about severity here
    # on purpose.
    sh:property [
        sh:path cpol:operator ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:nodeKind sh:Literal ;
        sh:pattern "{_operator_pattern()}" ;
        sh:message "Clause 5: the operator must be one of the closed set. An operator outside it is a non-conforming document and, at evaluation time, a refusal." ;
    ] ;

    sh:property [
        sh:path cpol:expected ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:message "A condition must carry cpol:expected. A condition with nothing to compare against cannot be evaluated, and is refused." ;
    ] .
"""


def served_path() -> Path:
    return (Path(__file__).resolve().parent.parent
            / "docs" / "ns" / PROFILE_VERSION / "shapes.ttl")


def main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(
        prog="croissant_policy.shapes",
        description="Generate the SHACL shapes for the static conformance clauses",
    )
    ap.add_argument("--write", action="store_true",
                    help="write docs/ns/<version>/shapes.ttl instead of stdout")
    args = ap.parse_args(argv)

    text = shapes()
    if args.write:
        path = served_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"shapes: -> {path}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
